apiVersion: v1
kind: Service
metadata:
  name: sre-app-service
  namespace: app
  labels:
    app: sre-app
spec:
  type: LoadBalancer
  selector:
    app: sre-app
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http  # This name must match the ServiceMonitor port name